version: "3"
services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-u",
          "root",
          "--password=$MYSQL_ROOT_PASS",
        ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ../../../database/DB:/var/lib/mysql
      - ../../../services/auth/migrations:/docker-entrypoint-initdb.d/


  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "$REDIS_PASSWORD"]
    volumes:
      - ../../../database/redis/data:/data
      - ../../../database/redis/redis.conf:/usr/local/etc/redis/redis.conf
