version: "3"
services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: password
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-u",
          "root",
          "--password=$$MYSQL_ROOT_PASSWORD",
        ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ../../DB:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/initsql
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysqldb
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - mysqldb
    networks:
      - mysql-phpmyadmin

  nginx:
    image: nginx:latest
    container_name: nginx-webserver
    volumes:
      - ../../nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
    depends_on: 
      - phpmyadmin

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ../../otelCollector/otel-collector.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "55670:55679" # zpages extension
    depends_on:
      - jaeger

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ../../otelCollector/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - otel-collector

  jaeger:
    image: jaegertracing/all-in-one:1.52
    container_name: jaeger
    ports:
      - 16686:16686
      - "14268"
      - "14250"

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx-paymentku
  #   restart: always
  #   ports:
  #     - 8880:80
  #   volumes:
  #     - ../../nginx/nginx.conf:/etc/nginx/nginx.conf

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ../../redis/data:/data
      - ../../redis/redis.conf:/usr/local/etc/redis/redis.conf

networks:
  mysql-phpmyadmin:
