services:
  mysqldb:
    image: mysql:9.1
    container_name: mysqldb
    restart: on-failure
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWD}
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-u",
          "root",
          "--password=$$MYSQL_ROOT_PASSWORD",
        ]   
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mysqldb:/var/lib/mysql
      - ../../database/table.sql:/docker-entrypoint-initdb.d/initsql

  # otel-collector:
  #   image: otel/opentelemetry-collector-contrib:0.118.0
  #   container_name: otel-collector
  #   command: ["--config=/etc/otel-collector-config.yaml"]
  #   volumes:
  #     - ../../../observability/otel-collector.yaml:/etc/otel-collector-config.yaml
  #   ports:
  #     - "127.0.0.1:1888:1888" # pprof extension
  #     - "127.0.0.1:8888:8888" # Prometheus metrics exposed by the collector
  #     - "127.0.0.1:8889:8889" # Prometheus exporter metrics
  #     - "127.0.0.1:13133:13133" # health_check extension
  #     - "127.0.0.53:4317:4317" # OTLP gRPC receiver
  #     - "127.0.0.1:55670:55679" # zpages extension
  #   depends_on:
  #     - jaeger

  # prometheus:
  #   image: prom/prometheus:v3.0.1
  #   container_name: prometheus
  #   volumes:
  #     - ../../../observability/prometheus.yaml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "127.0.0.1:9090:9090"
  #   depends_on:
  #     - otel-collector

  # jaeger:
  #   image: jaegertracing/all-in-one:1.65.0
  #   container_name: jaeger
  #   ports:
  #     - "127.0.0.1:16686:16686"
  #     - "127.0.0.1:32783:14268"
  #     - "127.0.0.1:32782:4250"

  redis:
    image: redis:7.4.1
    container_name: redis
    restart: on-failure
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
      - ../../database/redis/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
   mysqldb:
   redis_data:
