name: CI

on:
  push:
    branches:
      - master
      - develop
      - features*
  pull_request:
    branches:
      - master

jobs:
  testing:
    name: Development processes
    runs-on: ubuntu-22.04
    steps:
      - name: Check Repository
        uses: actions/checkout@v4

      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0

      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Prune all Docker volumes (dangerous)
        run: docker volume prune -f

      - name: Setup Project
        run: |
          make install
      
      - name: Running docker compose 
        run: |
          make compose-cicd
      
      - name: Test auth service
        run: |
          make test-auth
     
      - name: Test transactional service
        run: make test-transactional
      
      - name: Down
        run: make down
    
  build:
    name: Staging
    runs-on: ubuntu-22.04
    needs: testing
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login into docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

        # TRANSACTION SERVICE START
      - name: Deploy transaction service to dockerhub
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:services/transaction"
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/transactional_paymentku:${{secrets.DOCKER_TAGS_PAYMENTKU}}

        # TRANSACTION SERVICE END

        # AUTH SERVICE START
      - name: Deploy auth service to dockerhub
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:services/auth"
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/auth_paymentku:${{secrets.DOCKER_TAGS_PAYMENTKU}}

        # AUTH SERVICE END

        # FRONTEND APP START
      - name: Deploy frontend service to dockerhub
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:www"
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/frontend_paymentku:${{secrets.DOCKER_TAGS_PAYMENTKU}}
        # FRONTEND APP END
