name: CI

on:
  push:
    branches:
      - main
      - develop
      - features*

jobs:
  develop:
    name: Development processes
    runs-on: ubuntu-22.04
    steps:
      - name: Check Repository
        uses: actions/checkout@v4

      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 21.0.0

      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run docker compose
        run: |
          make test-start

        # AUTH SERVICE START
      - name: Download dependencies in auth service
        working-directory: ./services/auth
        run: |
          npm install

      # - name: Run eslint for auth service
      #   working-directory: ./services/auth
      #   run: |
      #     npm run lint
    
      - name: test env
        run: |
         printenv


      - name: Test auth service
        run: |
          make test-auth
      # AUTH SERVICE END
      # HISTORY SERVICE START
      - name: Download dependencies in history service
        working-directory: ./services/history
        run: go mod download

      - name: Test history service
        working-directory: .
        run: make test-history

      # HISTORY SERVICE END
      # TRANSACTION SERVICE START
      - name: Download dependencies in transaction service
        working-directory: ./services/transaction
        run: go mod download

      - name: Test transaction service
        run: make test-transaction
      # TRANSACTION SERVICE END
      # USER SERVICE START
      - name: Download dependencies in user service
        working-directory: ./services/user
        run: go mod download

      - name: Test user service
        run: make test-user
      # USER SERVICE END

      # FRONTEND START
      - name: Download dependencies in frontend app
        working-directory: ./www
        run: npm install

      # - name: Run eslint for frontend app
      #   working-directory: ./www
      #   run: npm run lint
      # FRONTEND ENV

  staging:
    name: Staging
    runs-on: ubuntu-22.04
    needs: develop
    if: ${{github.ref == 'refs/heads/develop'}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login into docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

        # HISTORY SERVICE START
      - name: Deploy history service to dockerhub
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:services/history"
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/history_paymentku:${{secrets.DOCKER_TAGS_PAYMENTKU}}

        # HISTORY SERVICE END

        # TRANSACTION SERVICE START
      - name: Deploy transaction service to dockerhub
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:services/transaction"
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/transaction_paymentku:${{secrets.DOCKER_TAGS_PAYMENTKU}}

        # TRANSACTION SERVICE END

        # USER SERVICE START
      - name: Deploy user service to dockerhub
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:services/user"
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/user_paymentku:${{secrets.DOCKER_TAGS_PAYMENTKU}}
        # USER SERVICE END

        # AUTH SERVICE START
      - name: Deploy auth service to dockerhub
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:services/auth"
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/auth_paymentku:${{secrets.DOCKER_TAGS_PAYMENTKU}}

        # AUTH SERVICE END

        # FRONTEND APP START
      - name: Deploy frontend service to dockerhub
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:www"
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/frontend_paymentku:${{secrets.DOCKER_TAGS_PAYMENTKU}}
        # FRONTEND APP END
